django_nov/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import home, reservation_success
from account.views import UserLoginView, UserRegistrationView, logout_view
from django_nov import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('/reservation', reservation_success, name='reservation_success'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),
    path('cart/', include('order.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import booking_data, booking_confirm

app_name = 'manager'

urlpatterns = [
    path('booking/', booking_data, name='booking'),
    path('booking/<int:pk>/', booking_confirm, name='booking_confirm'),
]

order/urls.py
from django.urls import path
from .views import add_to_cart, view_cart, remove_from_cart, order_success

urlpatterns = [
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('view_cart/', view_cart, name='view_cart'),
    path('remove_from_cart/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('order_success/', order_success, name='order_success'),
]

templates/includes/footer.html
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  {{ location }}
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call {{ number }}
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  {{ email }}
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              Feane
            </a>
            <p>
              {{ text }}
            </p>
            <div class="footer_social">
              <a href="{{ facebook_link }}">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="{{ twitter_link }}">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="{{ linkedin_link }}">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="{{ instagram_link }}">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="{{ pinterest_link }}">
                <i class="fa fa-pinterest" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            {{ opening_hours|safe }}
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By
          <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
        </p>
      </div>
    </div>
  </footer>

templates/includes/header.html
{% load is_manager_tag %}
<header class="header_section">
  <div class="container">
    <nav class="navbar navbar-expand-lg custom_nav-container ">
      <a class="navbar-brand" href="{% url 'home' %}">
        <span>
          Feane
        </span>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class=""> </span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav  mx-auto ">
          <li class="nav-item {% if request.path == '/' %}active{% endif %}">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% if request.path == '#products' %}active{% endif %}">
            <a class="nav-link" href="{% url 'home' %}#products">Menu</a>
          </li>
          <li class="nav-item {% if request.path == '#abouts' %}active{% endif %}">
            <a class="nav-link" href="{% url 'home' %}#abouts">About</a>
          </li>
          <li class="nav-item {% if request.path == '#book' %}active{% endif %}">
            <a class="nav-link" href="{% url 'home' %}#book">Book.Table</a>
          </li>
          {% if not user.is_authenticated %}
          <li class="nav-item {% if request.path == '/register/' %}active{% endif %}">
            <a class="nav-link" href="{% url 'register' %}">Registration</a>
          </li>
          {% elif user|is_manager_tag %}
          <li class="nav-item {% if request.path == '/manager/booking/' %}active{% endif %}">
            <a class="nav-link" href="{% url 'manager:booking' %}">Reservations</a>
          </li>
          {% endif %}
        </ul>
        <div class="user_option">
          {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="user_link">{{ user }}</a>
          {% else %}
          <a href="{% url 'login' %}" class="user_link">
            <i class="fa fa-user" aria-hidden="true"></i>
          </a>
          {% endif %}
          <a class="cart_link" href="{% url 'view_cart' %}">
            <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
              <g>
                <g>
                  <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                   c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                </g>
              </g>
              <g>
                <g>
                  <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                   C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                   c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                   C457.728,97.71,450.56,86.958,439.296,84.91z" />
                </g>
              </g>
              <g>
                <g>
                  <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                   c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                </g>
              </g>
            </svg>
          </a>
            <a href="https://www.google.com/search?hl=en&tbm=isch&q=burgers" target="_blank">
                <button class="btn my-2 my-sm-0 nav_search-btn" type="button">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </a>
          <a href="{% url 'view_cart' %}" class="order_online">
            Order Online
          </a>
        </div>
      </div>
    </nav>
  </div>
</header>

templates/includes/slider.html
    <section class="slider_section ">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            {% for slider in slides %}
                {% if forloop.first %}
                    <div class="carousel-item active">
                        <div class="container ">
                            <div class="row">
                                <div class="col-md-7 col-lg-6 ">
                                    <div class="detail-box">
                                        <h1>
                                            {{ slider.name }}
                                        </h1>
                                        <p>
                                            {{ slider.text }}
                                        </p>
                                        <div class="btn-box">
                                            <a href="{% url 'view_cart' %}" class="btn1">
                                                Order Now
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="carousel-item ">
                        <div class="container ">
                            <div class="row">
                                <div class="col-md-7 col-lg-6 ">
                                    <div class="detail-box">
                                        <h1>
                                            {{ slider.name }}
                                        </h1>
                                        <p>
                                            {{ slider.text }}
                                        </p>
                                        <div class="btn-box">
                                            <a href="{% url 'view_cart' %}" class="btn1">
                                                Order Now
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="container">
          <ol class="carousel-indicators">
              {% for slider in slides %}
                  {% if forloop.first %}
                      <li data-target="#customCarousel1" data-slide-to="{{ slider.sort }}" class="active"></li>
                  {% else %}
                      <li data-target="#customCarousel1" data-slide-to="{{ slider.sort }}"></li>
                  {% endif %}
              {% endfor %}
          </ol>
        </div>
      </div>

    </section>