django_nov/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import home, reservation_success
from account.views import UserLoginView, UserRegistrationView, logout_view
from django_nov import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('/reservation', reservation_success, name='reservation_success'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),
    path('cart/', include('order.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import booking_data, booking_confirm

app_name = 'manager'

urlpatterns = [
    path('booking/', booking_data, name='booking'),
    path('booking/<int:pk>/', booking_confirm, name='booking_confirm'),
]

order/urls.py
from django.urls import path
from .views import add_to_cart, view_cart, remove_from_cart, order_success

urlpatterns = [
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('view_cart/', view_cart, name='view_cart'),
    path('remove_from_cart/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('order_success/', order_success, name='order_success'),
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from main.models import Reservation

def is_manager(user):
    return user.groups.filter(name='manager').exists() or user.is_superuser
# Create your views here.
@login_required(login_url='login')
@user_passes_test(is_manager)
def booking_data(request):
    data = Reservation.objects.filter(is_confirmed=False).order_by('-date')
    context = {'items': data}
    return render(request,'reservations.html', context=context)

def booking_confirm(request,pk):
    data = Reservation.objects.get(pk=pk)
    data.is_confirmed = True
    data.save()
    return redirect('manager:booking')

manager/templates/reservations.html
{% extends 'index.html' %}

{% block content %}

  <section class="booking">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Reservations
        </h2>
      <div class="filters-content">
        <div class="row grid">
        <div class="col-sm-6 col-lg-4 all">
            {% for item in items %}
                <div>
                    <div>{{ item.name }}</div>
                    <div>{{ item.phone }}</div>
                    <div>{{ item.email }}</div>
                    <div>{{ item.count }}</div>
                    <div>{{ item.date }}</div>
                <div><a href="{% url 'manager:booking_confirm' item.pk %}">Confirm</a></div>
                </div>
            {% endfor %}

          </div>
        </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}